spring:
  thymeleaf:
    cache: false

  h2:
    console:
      enabled: true
      path: "/console"
  datasource:
    url: "jdbc:h2:file:C:/Users/pavel/IdeaProjects/TacoCloud/db"
  jpa:
    hibernate:
      ddl-auto: validate